build:
  stage: build
  only:
    - master
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"

test:
  stage: test
  only:
    - master
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle